application:
  base_url: "http://127.0.0.1"
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  authorization_token: "secret-token"
  sender_email: "user@mail.com"
  timeout_ms: 10000
